apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "sf-tiltak-avtale"
  namespace: "team-dialog"
  labels:
    "team": "team-dialog"
    "start.nais.io/created-by": "me"
    "start.nais.io/creationTimestamp": "2022-10-19T04:24:54.264635067"
spec:
  image: {{image}}
  liveness:
    path: "/isalive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/isready"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses: 
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}